### ISSUE TITLE
Error Encounter 

### ISSUE THREAD

**Issue by HBegali** [PaulRegnier/PICAFlow#3]
Dear all, 
Please let me know if these errors are to be fixed. see attached 
The pipeline works fine with 32 GB RAM in my local machine for your preprocessed datasets.
I would like to run it for our cooperation datasets
I am getting a new error that is not related to limited RAM as below
The merageSample works fine but with launchTransformationTuningshinyApp

![image](https://github.com/user-attachments/assets/acd705ad-1273-4e4a-bf11-0faceb9e731c)

I got the same error when I tried to reduce the total number of files as below 
![image](https://github.com/user-attachments/assets/0b0c8ef3-62e4-4c3f-9663-a059e4feadd3)

Thanks in advance!
Best regards, Hanan

**Comment by PaulRegnier** [comment]
Hello @HBegali,

This precise issue was fixed in the latest version of PICAFlow, please see the associated commit: [https://github.com/PaulRegnier/PICAFlow/commit/abaad3fdc07795a7bd18f65d0a975d2871a7aa43](https://github.com/PaulRegnier/PICAFlow/commit/abaad3fdc07795a7bd18f65d0a975d2871a7aa43)

I kindly invite you to update PICAFlow using the following command:

`devtools::install_github("PaulRegnier/PICAFlow")`

Additionally, we plan to integrate very shortly an automatic version check during PICAFlow loading, in order to warn users about a new update. This will come very soon.

**Comment by HBegali** [comment]
@PaulRegnier thanks 👍
